<a href="https://colab.research.google.com/github/abduyea/Career-Trends-Analyzer/blob/main/notebooks/data_cleaning_and_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning and Preprocessing

loads the master job-postings dataset, performs basic data cleaning, and runs exploratory data analysis (EDA) to prepare a clean datasets

In [13]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import sys
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/Career-Trends-Analyzer").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_loader import (
    mount_drive,
    load_postings,
    load_companies,
    load_jobs,
    load_mappings,
    build_master,
)
from src.config import ROOT_DIR, RAW_DIR, DATA_DIR
from src.utils import peek, missing_summary, summarize_tables

import pandas as pd

print("ROOT_DIR:", ROOT_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ROOT_DIR: /content/drive/MyDrive/Career-Trends-Analyzer

Load Data and Build Master

In [14]:
mount_drive()

postings = load_postings()
companies = load_companies()
jobs = load_jobs()
mappings = load_mappings()

master = build_master(postings, companies, jobs, mappings)

print("Raw master shape:", master.shape)
peek(master)

# work on a copy
df = master.copy()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Raw master shape: (123849, 47)
(123849, 47)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,zip_code_company,address,url,salary_id,max_salary_salary,med_salary_salary,min_salary_salary,pay_period_salary,currency_salary,compensation_type_salary
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,07302,242 Tenth Street,https://www.linkedin.com/company/corcoran-sawy...,18531.0,20.0,NaN,17.0,HOURLY,USD,BASE_SALARY
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,NaN,NaN,8059.0,50.0,NaN,30.0,HOURLY,USD,BASE_SALARY
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,45227,6880 Wooster Pike,https://www.linkedin.com/company/the-national-...,14949.0,65000.0,NaN,45000.0,YEARLY,USD,BASE_SALARY
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,11042,3 Dakota Drive,https://www.linkedin.com/company/abrams-fenste...,11204.0,175000.0,NaN,140000.0,YEARLY,USD,BASE_SALARY
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,NaN,NaN,20809.0,80000.0,NaN,60000.0,YEARLY,USD,BASE_SALARY

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 47 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
 31  name                        122130 non-null  object
 32  description_company         121087 non-null  object
 33  company_size                117142 non-null  float64
 34  state                       122092 non-null  object
 35  country                     122131 non-null  object
 36  city                        122129 non-null  object
 37  zip_code_company            121866 non-null  object
 38  address                     122080 non-null  object
 39  url                         122131 non-null  object
 40  salary_id                   36073 non-null   float64
 41  max_salary_salary           29793 non-null   float64
 42  med_salary_salary           6280 non-null    float64
 43  min_salary_salary           29793 non-null   float64
 44  pay_period_salary           36073 non-null   object
 45  currency_salary             36073 non-null   object
 46  compensation_type_salary    36073 non-null   object
dtypes: float64(19), int64(2), object(26)
memory usage: 44.4+ MB

In [16]:
# Summary for numeric columns
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
job_id,123849.0,NaN,NaN,NaN,3896402138.074615,84043545.161881,921716.0,3894586595.0,3901998406.0,3904707077.0,3906267224.0
company_name,122130,24428,Liberty Healthcare and Rehabilitation Services,1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,123849,72521,Sales Manager,673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,123842,107827,Position Summary: Our Sales Manager has managi...,474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max_salary,29793.0,NaN,NaN,NaN,91939.423461,701110.138622,1.0,48.28,80000.0,140000.0,120000000.0
pay_period,36073,5,YEARLY,20628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,123849,8526,United States,8125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_id,122132.0,NaN,NaN,NaN,12204012.335015,25541431.65742,1009.0,14352.0,226965.0,8047188.0,103472979.0
views,122160.0,NaN,NaN,NaN,14.618247,85.903598,1.0,3.0,4.0,8.0,9975.0
med_salary,6280.0,NaN,NaN,NaN,22015.619876,52255.873846,0.0,18.94,25.5,2510.5,750000.0
min_salary,29793.0,NaN,NaN,NaN,64910.847434,495973.793504,1.0,37.0,60000.0,100000.0,85000000.0
formatted_work_type,123849,7,Full-time,98814,NaN,NaN,NaN,NaN,NaN,NaN,NaN
applies,23320.0,NaN,NaN,NaN,10.591981,29.047395,1.0,1.0,3.0,8.0,967.0
original_listed_time,123849.0,NaN,NaN,NaN,1713152338799.941406,484820878.414716,1701810533000.0,1712862876000.0,1713395039000.0,1713478324000.0,1713572803000.0
remote_allowed,15246.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
job_posting_url,123849,123849,https://www.linkedin.com/jobs/view/3906267224/...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
application_url,87184,84800,https://app.dataannotation.tech/worker_signup?...,205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
application_type,123849,4,OffsiteApply,84607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
expiry,123849.0,NaN,NaN,NaN,1716213036608.151855,2321393898.084225,1712903448000.0,1715480718000.0,1716042264000.0,1716088229000.0,1729124796000.0
closed_time,1073.0,NaN,NaN,NaN,1712927892086.672852,362289347.409251,1712345932000.0,1712669760000.0,1712669910000.0,1713282569000.0,1713562107000.0
formatted_experience_level,94440,6,Mid-Senior level,41489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
skills_desc,2439,2212,This position requires the following skills: E...,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
listed_time,123849.0,NaN,NaN,NaN,1713204445996.681396,398912198.594052,1711317014000.0,1712885544000.0,1713407593000.0,1713483628000.0,1713572816000.0
posting_domain,83881,4443,www.click2apply.net,3811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sponsored,123849.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
work_type,123849,7,FULL_TIME,98814,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,36073,6,USD,36058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compensation_type,36073,1,BASE_SALARY,36073,NaN,NaN,NaN,NaN,NaN,NaN,NaN
normalized_salary,36073.0,NaN,NaN,NaN,205327.03685,5097626.762136,0.0,52000.0,81500.0,125000.0,535600000.0
zip_code,102977.0,NaN,NaN,NaN,50400.491887,30252.232515,1001.0,24112.0,48059.0,78201.0,99901.0
fips,96434.0,NaN,NaN,NaN,28713.879887,16015.929825,1003.0,13121.0,29183.0,42077.0,56045.0
name,122130,24428,Liberty Healthcare and Rehabilitation Services,1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description_company,121087,24164,Liberty Healthcare and Rehabilitation Services...,1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_size,117142.0,NaN,NaN,NaN,4.93542,2.054749,1.0,3.0,5.0,7.0,7.0
state,122092,788,0,8521,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,122131,81,US,109995,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,122129,4124,New York,7149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zip_code_company,121866,7779,0,11685,NaN,NaN,NaN,NaN,NaN,NaN,NaN
address,122080,19476,0,13436,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,122131,24473,https://www.linkedin.com/company/liberty-healt...,1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary_id,36073.0,NaN,NaN,NaN,20485.492945,11660.288556,1.0,10502.0,20476.0,30434.0,40785.0
max_salary_salary,29793.0,NaN,NaN,NaN,91939.423461,701110.138622,1.0,48.28,80000.0,140000.0,120000000.0
med_salary_salary,6280.0,NaN,NaN,NaN,22015.619876,52255.873846,0.0,18.94,25.5,2510.5,750000.0
min_salary_salary,29793.0,NaN,NaN,NaN,64910.847434,495973.793504,1.0,37.0,60000.0,100000.0,85000000.0
pay_period_salary,36073,5,YEARLY,20628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency_salary,36073,6,USD,36058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compensation_type_salary,36073,1,BASE_SALARY,36073,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:

def column_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = pd.DataFrame({
        "dtype": df.dtypes,
        "missing_count": df.isna().sum(),
        "missing_percent": (df.isna().mean() * 100).round(2),
        "unique_values": df.nunique(),
        "sample_values": df.apply(lambda x: x.dropna().unique()[:5])
    })
    return summary

column_summary(df)

,dtype,missing_count,missing_percent,unique_values,sample_values
job_id,int64,0,0.00,123849,"[921716, 1829192, 10998357, 23221523, 35982263]"
company_name,object,1719,1.39,24428,"[Corcoran Sawyer Smith, The National Exemplar ..."
title,object,0,0.00,72521,"[Marketing Coordinator, Mental Health Therapis..."
description,object,7,0.01,107827,[Job descriptionA leading real estate firm in ...
max_salary,float64,94056,75.94,5321,"[20.0, 50.0, 65000.0, 175000.0, 80000.0]"
pay_period,object,87776,70.87,5,"[HOURLY, YEARLY, MONTHLY, WEEKLY, BIWEEKLY]"
location,object,0,0.00,8526,"[Princeton, NJ, Fort Collins, CO, Cincinnati, ..."
company_id,float64,1717,1.39,24474,"[2774458.0, 64896719.0, 766262.0, 1481176.0, 8..."
views,float64,1689,1.36,684,"[20.0, 1.0, 8.0, 16.0, 3.0]"
med_salary,float64,117569,94.93,1417,"[350.0, 25.0, 23.0, 56.41, 4200.0]"
min_salary,float64,94056,75.94,4612,"[17.0, 30.0, 45000.0, 140000.0, 60000.0]"
formatted_work_type,object,0,0.00,7,"[Full-time, Internship, Contract, Part-time, T..."
applies,float64,100529,81.17,274,"[2.0, 4.0, 1.0, 49.0, 12.0]"
original_listed_time,float64,0,0.00,65036,"[1713397508000.0, 1712857887000.0, 17132776140..."
remote_allowed,float64,108603,87.69,1,[1.0]
job_posting_url,object,0,0.00,123849,[https://www.linkedin.com/jobs/view/921716/?tr...
application_url,object,36665,29.60,84800,"[www.childrensnebraska.org, https://www.kidsbo..."
application_type,object,0,0.00,4,"[ComplexOnsiteApply, SimpleOnsiteApply, Offsit..."
expiry,float64,0,0.00,54851,"[1715989508000.0, 1715449887000.0, 17158696140..."
closed_time,float64,122776,99.13,698,"[1713207715000.0, 1713212227000.0, 17134636930..."
formatted_experience_level,object,29409,23.75,6,"[Entry level, Mid-Senior level, Associate, Dir..."
skills_desc,object,121410,98.03,2212,[Requirements: \r\n\r\nWe are seeking a Colleg...
listed_time,float64,0,0.00,53231,"[1713397508000.0, 1712857887000.0, 17132776140..."
posting_domain,object,39968,32.27,4443,"[arrowstaffingservices.thejobnetwork.com, will..."
sponsored,int64,0,0.00,1,[0]
work_type,object,0,0.00,7,"[FULL_TIME, INTERNSHIP, CONTRACT, PART_TIME, T..."
currency,object,87776,70.87,6,"[USD, CAD, BBD, EUR, AUD]"
compensation_type,object,87776,70.87,1,[BASE_SALARY]
normalized_salary,float64,87776,70.87,7259,"[38480.0, 83200.0, 55000.0, 157500.0, 70000.0]"
zip_code,float64,20872,16.85,6989,"[8540.0, 80521.0, 45202.0, 11040.0, 52601.0]"
fips,float64,27415,22.14,2270,"[34021.0, 8069.0, 39061.0, 36059.0, 19057.0]"
name,object,1719,1.39,24428,"[Corcoran Sawyer Smith, The National Exemplar ..."
description_company,object,2762,2.23,24164,[With years of experience helping local buyers...
company_size,float64,6707,5.42,7,"[2.0, 1.0, 5.0, 3.0, 4.0]"
state,object,1757,1.42,788,"[NJ, Ohio, New York, North Carolina, CA]"
country,object,1718,1.39,81,"[US, TW, 0, GB, IR]"
city,object,1720,1.39,4124,"[Jersey City, Mariemont, Lake Success, Raleigh..."
zip_code_company,object,1983,1.60,7779,"[07302, 45227, 11042, 27601, 90017]"
address,object,1769,1.43,19476,"[242 Tenth Street, 6880 Wooster Pike, 3 Dakota..."
url,object,1718,1.39,24473,[https://www.linkedin.com/company/corcoran-saw...
salary_id,float64,87776,70.87,36073,"[18531.0, 8059.0, 14949.0, 11204.0, 20809.0]"
max_salary_salary,float64,94056,75.94,5321,"[20.0, 50.0, 65000.0, 175000.0, 80000.0]"
med_salary_salary,float64,117569,94.93,1417,"[350.0, 25.0, 23.0, 56.41, 4200.0]"
min_salary_salary,float64,94056,75.94,4612,"[17.0, 30.0, 45000.0, 140000.0, 60000.0]"
pay_period_salary,object,87776,70.87,5,"[HOURLY, YEARLY, MONTHLY, WEEKLY, BIWEEKLY]"
currency_salary,object,87776,70.87,6,"[USD, CAD, BBD, EUR, AUD]"
compensation_type_salary,object,87776,70.87,1,[BASE_SALARY]

In [19]:
# Missing values count
df.isnull().sum()

# Missing value percentage
(df.isnull().mean() * 100).round(2)

job_id                         0.00
company_name                   1.39
title                          0.00
description                    0.01
max_salary                    75.94
pay_period                    70.87
location                       0.00
company_id                     1.39
views                          1.36
med_salary                    94.93
min_salary                    75.94
formatted_work_type            0.00
applies                       81.17
original_listed_time           0.00
remote_allowed                87.69
job_posting_url                0.00
application_url               29.60
application_type               0.00
expiry                         0.00
closed_time                   99.13
formatted_experience_level    23.75
skills_desc                   98.03
listed_time                    0.00
posting_domain                32.27
sponsored                      0.00
work_type                      0.00
currency                      70.87
compensation_type             70.87
normalized_salary             70.87
zip_code                      16.85
fips                          22.14
name                           1.39
description_company            2.23
company_size                   5.42
state                          1.42
country                        1.39
city                           1.39
zip_code_company               1.60
address                        1.43
url                            1.39
salary_id                     70.87
max_salary_salary             75.94
med_salary_salary             94.93
min_salary_salary             75.94
pay_period_salary             70.87
currency_salary               70.87
compensation_type_salary      70.87
dtype: float64